### ISSUE TITLE
Redesign asset extraction

### ISSUE THREAD

**Issue by rhysrevans3** [cedadev/extraction-methods#3]
possible new config:
```
- method: asset
   inputs: 
     gen_method:
        method: elasticsearch
        inputs: 
          input_1: hello
          input_2: world
     extraction_methods:
       - method: regex
          inputs: 
            regex: "{hello}"
```
